FROM python:3.12
RUN pip install poetry
LABEL maintainer = "ch.wasam@gmail.com"
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /code
COPY . /code/
RUN poetry install
RUN poetry config virtualenvs.create false
EXPOSE 8000
CMD ["poetry","run","uvicorn","my_first_fastapi_docker.main:app","--host","0.0.0.0", "--reload"]
