version: "0.0.1"
services: 
  jupyter:
    container_name: "jupyter"
    hostname: "jupyter"
    build:
      context: ./code
    ports:
      - "8888:8888"
    volumes:
      - ./code:/code/
    networks:
      - my-api-net

  backend:
    container_name: "backend"
    hostname: "backend"
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/
    networks:
      - my-api-net

networks:
  my-api-net:
    driver: bridge