name: project-01
services:

  api:
    container_name: "product"
    hostname: "product"
    build:
      context: ./product_service_01
      dockerfile: Dockerfile.dev
    depends_on:
        - postgres_db
    ports:
      - "8085:8085"  # Expose container port 8000 to host port 8000  
    volumes:
      - ./product_service_01:/code/




  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
        - POSTGRES_USER=wasam
        - POSTGRES_PASSWORD=wasam_password
        - POSTGRES_DB=wasam_database
    ports:
        - '5433:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data





volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge