version: 1.0.1
name: "generate_access_token"
services:
  auth-api-service:
    build:
      context: ./access_token
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./access_token:/code
    networks:
      - auth-network

networks:
  auth-network:
